# Generated by Django 3.1.7 on 2022-05-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='academic_title',
            field=models.CharField(blank=True, choices=[('PROF', 'Prof.'), ('DR', 'Dr.')], max_length=10),
        ),
        migrations.AddField(
            model_name='workinggroup',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
