name: "Bug Report"
description: Creatre a new issue for a bug.
title: "[BUG] - <title>"
labels: ["bug", "needs triage"]

body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: textarea
    id: expected_behaviour
    attributes:
      label: "Expected Behaviour"
      description: Please describe how you would expect the app to behave
      placeholder: I would expect the app to ... because ...
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description of your issue
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      descriptions: Speciy whether the bug occured on prod or test environment.
      placeholder: e.g. https://www.test-pledge4future.org
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: bash
    validations:
      required: false
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: "Browsers"
      description: What browsers are you seeing the problem on ?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
    validations:
      required: false
  - type: textarea
    id: browser_version
    attributes:
      label: "Browser Version"
      description: The version of the browser you are using.
    validations:
      required: false
  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: How urgent is a fix in your opinion?
      options:
        - Low
        - Medium
        - High
    validations:
      required: true
