name: Issue Template
about: Create a new issue
title: ""

body:
  - type: select
    id: issue_type
    attributes:
      label: Issue Type
      description: Please select the type of issue you are creating.
      options:
        - Bug Report
        - Feature Request
        - General Issue

  - type: conditional
    attributes:
      conditions:
        - field: issue_type
          value: Bug Report
      items:
        - type: textarea
          id: bug_description
          attributes:
            label: Bug Description
            description: Provide a general description of the bug.

        - type: textarea
          id: expected_behavior
          attributes:
            label: Expected Behavior
            description: Describe the software behaviour that you would expect. This helps us identify whether this is actually a bug or if the app is working as intended.

        - type: enum
          id: reproduction_steps
          attributes:
            label: Reproduction Steps
            description: |
              Enumerate the steps to reproduce the bug.
              1. Step 1
              2. Step 2
              3. Step 3
              4. ...

        - type: text
          id: browser
          attributes:
            label: Browser and Version
            description: Specify the browser you are using. Please include the version.

        - type: select
          id: priority
          attributes:
            label: Priority
            description: Select the priority of the issue.
            options:
              - High
              - Medium
              - Low

    actions:
      - type: add_label
        name: Prio:HIGH
        if: ${{ inputs.priority == 'High' }}
        description: Adds 'Prio:High' label to the issue.
      - type: add_label
        name: Prio:MEDIUM
        if: ${{ inputs.priority == 'Medium' }}
        description: Adds 'Prio:Medium' label to the issue.
      - type: add_label
        name: Prio:LOW
        if: ${{ inputs.priority == 'Low' }}
        description: Adds 'Prio:Low' label to the issue.

  - type: conditional
    attributes:
      conditions:
        - field: issue_type
          value: Feature Request
      items:
        - type: textarea
          id: feature_description
          attributes:
            label: Feature Description
            description: Provide a general description of the feature.

        - type: text
          id: user_role
          attributes:
            label: User Role
            description: Describe your role in relation to this feature.

        - type: select
          id: priority
          attributes:
            label: Priority
            description: Select the priority of the feature request.
            options:
              - High
              - Medium
              - Low

    actions:
          - type: add_label
            name: Prio:HIGH
            if: ${{ inputs.priority == 'High' }}
            description: Adds 'Prio:High' label to the issue.
          - type: add_label
            name: Prio:MEDIUM
            if: ${{ inputs.priority == 'Medium' }}
            description: Adds 'Prio:Medium' label to the issue.
          - type: add_label
            name: Prio:LOW
            if: ${{ inputs.priority == 'Low' }}
            description: Adds 'Prio:Low' label to the issue.

  - type: conditional
    attributes:
      conditions:
        - field: issue_type
          value: General Issue
      items:
        - type: textarea
          id: general_description
          attributes:
            label: General Issue Description
            description: Here is room for your input if you are not sure whether your issue is Bug or a Feature Request. Please provide a detailed description of the issue and add labels if necessary.
