name: Backend Build

on:
  push:
    branches:
      - dev
  
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "SECRET_KEY=mock_secret_key_for_django" >> $GITHUB_ENV

      - name: Run tests
        run: python ./src/manage.py test